/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeveloperIndexRouteImport } from './routes/developer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as GameGameSlugRouteImport } from './routes/game/$gameSlug'
import { Route as DeveloperManageGamesRouteImport } from './routes/developer/manage-games'
import { Route as DeveloperLayoutRouteImport } from './routes/developer/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameSlugRoute = GameGameSlugRouteImport.update({
  id: '/game/$gameSlug',
  path: '/game/$gameSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperManageGamesRoute = DeveloperManageGamesRouteImport.update({
  id: '/developer/manage-games',
  path: '/developer/manage-games',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperLayoutRoute = DeveloperLayoutRouteImport.update({
  id: '/developer/_layout',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminLayoutRoute
  '/developer': typeof DeveloperLayoutRoute
  '/developer/manage-games': typeof DeveloperManageGamesRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/developer/': typeof DeveloperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/developer/manage-games': typeof DeveloperManageGamesRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/developer/_layout': typeof DeveloperLayoutRoute
  '/developer/manage-games': typeof DeveloperManageGamesRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/developer/': typeof DeveloperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/developer'
    | '/developer/manage-games'
    | '/game/$gameSlug'
    | '/profile/$userId'
    | '/admin/'
    | '/developer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/developer'
    | '/developer/manage-games'
    | '/game/$gameSlug'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/_layout'
    | '/developer/_layout'
    | '/developer/manage-games'
    | '/game/$gameSlug'
    | '/profile/$userId'
    | '/admin/'
    | '/developer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  DeveloperLayoutRoute: typeof DeveloperLayoutRoute
  DeveloperManageGamesRoute: typeof DeveloperManageGamesRoute
  GameGameSlugRoute: typeof GameGameSlugRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameSlug': {
      id: '/game/$gameSlug'
      path: '/game/$gameSlug'
      fullPath: '/game/$gameSlug'
      preLoaderRoute: typeof GameGameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/manage-games': {
      id: '/developer/manage-games'
      path: '/developer/manage-games'
      fullPath: '/developer/manage-games'
      preLoaderRoute: typeof DeveloperManageGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/_layout': {
      id: '/developer/_layout'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  DeveloperLayoutRoute: DeveloperLayoutRoute,
  DeveloperManageGamesRoute: DeveloperManageGamesRoute,
  GameGameSlugRoute: GameGameSlugRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
