/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameGameSlugRouteImport } from './routes/game/$gameSlug'
import { Route as AuthenticatedDeveloperIndexRouteImport } from './routes/_authenticated/developer/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile/$userId'
import { Route as AuthenticatedDeveloperManageGamesRouteImport } from './routes/_authenticated/developer/manage-games'
import { Route as AuthenticatedDeveloperLayoutRouteImport } from './routes/_authenticated/developer/_layout'
import { Route as AuthenticatedAdminLayoutRouteImport } from './routes/_authenticated/admin/_layout'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameSlugRoute = GameGameSlugRouteImport.update({
  id: '/game/$gameSlug',
  path: '/game/$gameSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeveloperIndexRoute =
  AuthenticatedDeveloperIndexRouteImport.update({
    id: '/developer/',
    path: '/developer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperManageGamesRoute =
  AuthenticatedDeveloperManageGamesRouteImport.update({
    id: '/developer/manage-games',
    path: '/developer/manage-games',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperLayoutRoute =
  AuthenticatedDeveloperLayoutRouteImport.update({
    id: '/developer/_layout',
    path: '/developer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLayoutRoute =
  AuthenticatedAdminLayoutRouteImport.update({
    id: '/admin/_layout',
    path: '/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
  '/admin': typeof AuthenticatedAdminLayoutRoute
  '/developer': typeof AuthenticatedDeveloperLayoutRoute
  '/developer/manage-games': typeof AuthenticatedDeveloperManageGamesRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/developer/': typeof AuthenticatedDeveloperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/developer': typeof AuthenticatedDeveloperIndexRoute
  '/developer/manage-games': typeof AuthenticatedDeveloperManageGamesRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
  '/_authenticated/admin/_layout': typeof AuthenticatedAdminLayoutRoute
  '/_authenticated/developer/_layout': typeof AuthenticatedDeveloperLayoutRoute
  '/_authenticated/developer/manage-games': typeof AuthenticatedDeveloperManageGamesRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/developer/': typeof AuthenticatedDeveloperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/game/$gameSlug'
    | '/admin'
    | '/developer'
    | '/developer/manage-games'
    | '/profile/$userId'
    | '/admin/'
    | '/developer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/game/$gameSlug'
    | '/admin'
    | '/developer'
    | '/developer/manage-games'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/game/$gameSlug'
    | '/_authenticated/admin/_layout'
    | '/_authenticated/developer/_layout'
    | '/_authenticated/developer/manage-games'
    | '/_authenticated/profile/$userId'
    | '/_authenticated/admin/'
    | '/_authenticated/developer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  GameGameSlugRoute: typeof GameGameSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameSlug': {
      id: '/game/$gameSlug'
      path: '/game/$gameSlug'
      fullPath: '/game/$gameSlug'
      preLoaderRoute: typeof GameGameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/developer/': {
      id: '/_authenticated/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof AuthenticatedDeveloperIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/manage-games': {
      id: '/_authenticated/developer/manage-games'
      path: '/developer/manage-games'
      fullPath: '/developer/manage-games'
      preLoaderRoute: typeof AuthenticatedDeveloperManageGamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/_layout': {
      id: '/_authenticated/developer/_layout'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/_layout': {
      id: '/_authenticated/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminLayoutRoute: typeof AuthenticatedAdminLayoutRoute
  AuthenticatedDeveloperLayoutRoute: typeof AuthenticatedDeveloperLayoutRoute
  AuthenticatedDeveloperManageGamesRoute: typeof AuthenticatedDeveloperManageGamesRoute
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDeveloperIndexRoute: typeof AuthenticatedDeveloperIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminLayoutRoute: AuthenticatedAdminLayoutRoute,
  AuthenticatedDeveloperLayoutRoute: AuthenticatedDeveloperLayoutRoute,
  AuthenticatedDeveloperManageGamesRoute:
    AuthenticatedDeveloperManageGamesRoute,
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDeveloperIndexRoute: AuthenticatedDeveloperIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  GameGameSlugRoute: GameGameSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
